services:
    pizzaminded_entable.example:
        class: pizzaminded\EntableBundle\Twig\Extension\EntableExtension
        public: true
        tags:
         - { name: twig.extension }
        arguments:
          twig: "@twig"
          translator: '@translator'
          router: '@router'
